### ISSUE TITLE
Sprint 2 - Review and Demo

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/27315-IntoTheDeep#15]

**Comment by Geckoing** [comment]
- [ ] Sprint 2 Successes:
- [ ] 
- [ ] Finished the Forearm and claw assembly
- [ ] Attached the forearm and claw assembly
- [ ] Helped various others with their tasks
- [ ] Prepared for coding
- [ ] 
- [ ] Sprint 2 Failures:
- [ ] 
- [ ] Did not find a way to achieve level 2 ascent
- [ ] Not done wiring 
- [ ] 
- [ ] Next Steps:
- [ ] 
- [ ] Prepare for coding
- [ ] Code for movement 
- [ ] Figure out how to achieve level 2 ascent
