### ISSUE TITLE
Sprint 3 - Review and Demo

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/27315-IntoTheDeep#22]

**Comment by Geckoing** [comment]
Successes:
- Figure out how to use the servo programmer and use its various functions to further pursue our other goals
- Program the servo
- Code the intake to spin forwards and backwards
- Design and then code a way to achieve a level 2 ascension

Failures:
- Design and then code a way to achieve a level 2 ascension (We need to completely finish the robot first, code and all)

Next Steps:
- Prepare vigorously for our inspection by ensuring everything is within the set parameters and is done according to the inspection manual
- Contribute any documentation needed to the team portfolio
- Assist with the finishing of code for the drivetrain and four bar assembly
- Practice our independent roles for competition (Driver, Coach etc.)
