### ISSUE TITLE
Sprint 4:  Team Portfolio

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/27315-IntoTheDeep#26]
PDF of Team Portfolio based on manual guidelines, with an emphasis on Think, Innovate and/or Control Award criteria.  Be sure review the [portfolio and award criteria  in the manual](https://ftc-resources.firstinspires.org/file/ftc/game/manual-06)

Define and assign the distribution of duties here and create the necessary sub issues. Be sure to set the necessary assignees and label (Portfolio) on related issues.

**Comment by Geckoing** [comment]
I will begin the portfolio and lay the groundwork for it while I wait for the others to complete their necessary tasks before joining me. So in short I will take lead on the completion of the team portfolio.
