### ISSUE TITLE
Sprint 4: Team Presentation

### ISSUE THREAD

**Issue by mrfabroa** [sta-titansrobotics/27315-IntoTheDeep#27]
Judging presentation: 5 min presentation + 10 minute Q & A (Nov 19, 20).   [Review manual for awards and presentation details](https://ftc-resources.firstinspires.org/file/ftc/game/manual-06)

Define and assign the distribution of duties here and create the necessary sub issues. Be sure to set the necessary assignees and label (Presentation) on related issues.

**Comment by Anand-nicrypto** [comment]
Once I have finished helping polish the Teleop code, I will begin to design the presentation. This means I will:

- Design the title page
- Look through the requirements
- Focus in highlighting the key details
- I am essentially building the exoskeleton/prototype of the presentation, then once we are finished with everything else, we can all help to fix it up
